### ISSUE TITLE
[react-native-graphql] Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'

### ISSUE THREAD

**Issue by dk0r** [graphcool-examples/react-native-graphql#6]
Receiving following error from the [authentication-with-auth0-and-apollo](https://github.com/graphcool-examples/react-native-graphql/tree/master/authentication-with-auth0-and-apollo) example:  
- [**Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'**](https://gist.github.com/dk0r/4b1115ad7e812926fef91ee9373346c3)

**Versions**:
- react-native@0.44.2
- Android studio [@2.3.2](http://i.imgur.com/lIAp2ih.png) 
- A virtual android device @ [API 23](http://i.imgur.com/SsIJzLl.png):

**Steps to reproduce**: 
- Unzip the [authentication-with-auth0-and-apollo](https://github.com/graphcool-examples/react-native-graphql/tree/master/authentication-with-auth0-and-apollo) example
- Install deps by doing `yarn` in main directory
- Incur the following error: [https://gist.github.com/dk0r/4b1115ad7e812926fef91ee9373346c3](https://gist.github.com/dk0r/4b1115ad7e812926fef91ee9373346c3)

**Expected behavior**: 
- App should build and run on android

**Solution**:
- Error is resolved by adding the following to the `android{ ... }` section in the **.../android/app/build.gradle** file:

 `packagingOptions {exclude 'META-INF/LICENSE' exclude 'META-INF/NOTICE'}`
- Here is a copy of my [build.gradle](https://gist.github.com/dk0r/c8151e01de590ad8e308eb20c478f1af) working without error on android [API-23](http://i.imgur.com/SsIJzLl.png)

**Note**:
-  **_This issue is likely occurring on all ([seven](https://github.com/graphcool-examples/react-native-graphql)) of Graphcool's react-native examples_**
- See Auth0's [manual configuration instructions](https://github.com/auth0/react-native-lock#manually-1) for details on correcting this and other errors you will incur with graphcool's react-native auth0 examples.

**Comment by marktani** [comment]
> Similar to these stackoverflow suggestions, this error may be avoided by including the following in the android{ } section of .../android/app/build.gradle

Did you try that workaround? Does it actually work? Would love a PR if that's the case 🙂

**Comment by dk0r** [comment]
yep, the work around was successful for the particular [react-native-graphql/authentication-with-auth0-and-apollo/Auth0Example/](https://github.com/graphcool-examples/react-native-graphql/tree/master/authentication-with-auth0-and-apollo/Auth0Example) example.

**Comment by marktani** [comment]
Thinking about this again, the `android` and `ios` folders are generated by `react-native` itself, so adjusting the automatically generated configurations might fix the symptoms but not the cause of the problems.

**Comment by dk0r** [comment]
@marktani I'm uncertain what the `android` or `ios` dirs have to do with this issue that is resolved by modifying the **build.gradle** file as described above. Perhaps you meant to reply to the [learnapollo/pokedex-react-native-vanilla](https://github.com/learnapollo/pokedex-react-native-vanilla/issues) issue which is missing it's `android` and `ios` dirs?

**Comment by marktani** [comment]
Well, `build.gradle` is a file that resides in the `android` directory. Could you find any information that addressed the root cause of this issue? Maybe it's a RN configuration problem.

**Comment by dk0r** [comment]
Unfortunately not. My only reference to a solution came from Auth0's [manual configuration instructions](https://github.com/auth0/react-native-lock#manually-1)

**Comment by marktani** [comment]
Ah, now I see what's happening. Indeed, this is then only a problem with the `authentication-with-auth0-and-apollo` example, because the cause of the problem is the `react-native-lock` module that's only needed for Auth0.

Thanks for digging through this!
